language: generic 
sudo: required
services:
    - docker

before_install:
    - docker build -t mkarmi/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true mkarmi/react-test npm test -- --coverage

after_success:
    - docker build -t mkarmi/multi-client ./client
    - docker build -t mkarmi/multi-nginx ./nginx
    - docker build -t mkarmi/mulit-server ./server
    - docker build -t mkarmi/worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push mkarmi/multi-client
    - docker push mkarmi/multi-nginx
    - docker push mkarmi/mulit-server
    - docker push mkarmi/worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-212624916226
    bucket_path : docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY